### ISSUE TITLE
"An attempt was made to break through the security policy of the user agent" when creating a new novel

### ISSUE THREAD

**Issue by robotlolita** [robotlolita/raven#83]
Happens Windows 8.1, typing any name at the "entry" screen and clicking "start writing":

``` text
Uncaught node.js Error

Error: An attempt was made to break through the security policy of the user agent.
  at Future.eval (www\scripts\main.js:39:32)
  at Future.eval(node_modules\data.future\lib\future.js:136:35)
  at Future.eval(node_modules\data.future\lib\future.js:136:35)
  at Object.exports.run (www\scripts\utils:29:12)
  at React.createClass.reload (www\scripts\screens\entry.js:169:23)
  at wrapper [as _onTimeout] (timers:252:14)
  at Timer.listOnTimeout [as ontimeout] (timers:110:15)
```

**Comment by x421** [comment]
Workaround for those who want to write: Create an empty .md file and "import" a book. :smile:

**Comment by sirodoht** [comment]
It happened to me too (OS X Yosemite).

Also, by clicking on the button instead of hitting 'Enter' the problem was solved.

**Comment by haskellcamargo** [comment]
And I miss the old icon. :disappointed:

**Comment by robotlolita** [comment]
@haskellcamargo old icon?

**Comment by haskellcamargo** [comment]
The book instead of this:
![icon](https://cloud.githubusercontent.com/assets/7553006/9615214/2bd20fde-50cd-11e5-9619-a9696a30eca4.PNG)

**Comment by robotlolita** [comment]
@haskellcamargo ah, that looks like a packaging error. Can you open a separate issue for this?

**Comment by hsandt** [comment]
Confirmed on Ubuntu 22.04. Error displays, then app auto-closes (crashes) a few seconds later.
Only happens the first time. Creating the project again (at least this same title) doesn't trigger the issue.
